[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  included_files = ["app/api/**/*"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"
    Cache-Control = "no-store"
    Pragma = "no-cache"

[forms]
  [forms.contact]
    name = "contact"
    fields = { name = "string", email = "string", phone = "string", message = "string" }
    notifications = [{ to = "info@poolcompliancesa.com.au", subject = "New Contact Form Submission" }]

  [forms.booking]
    name = "booking"
    fields = { firstName = "string", lastName = "string", email = "string", phone = "string", address = "string", suburb = "string", postcode = "string", preferredDate = "string", notes = "string", includeCprSign = "string", total = "string" }
    notifications = [{ to = "info@poolcompliancesa.com.au", subject = "New Pool Inspection Booking" }]

[functions.next]
  included_files = ["app/api/**/*"]
  external_node_modules = ["stripe"]
